resolver: nightly-2018-05-13
compiler: ghcjs-0.2.0.9011009_ghc-8.4.1
compiler-check: match-exact

packages:
 - '.'
extra-deps:
- miso-0.18.0.0
- git: https://github.com/ghcjs/ghcjs-base.git
  commit: 92bfcf42ffddb9676c4e288efd5750a06c4f4799

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9011009_ghc-8.4.1:
         url: /opt/ghcjs.tar.gz

allow-newer: true

